# Generated by Django 4.1.1 on 2022-10-04 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, default=1000, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('letra', models.CharField(default='A', max_length=100)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.maestro')),
            ],
        ),
    ]
