# Generated by Django 4.1.1 on 2022-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
    ]
